### ISSUE TITLE
Representing Data Objects VS Exchange Std

### ISSUE THREAD

**Issue by SeanCrimmins** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#10]
Decide how to distinguish between data exchanged e.g. Grid model and the exchange format e.g. IEC 61970/CGMES  and the protocol e.g. SOAP with RDF.

**Comment by lcrowleyEPRI** [comment]
I added the diagram called "High level DFD w Data Exchange Standards" which has a number of data exchange standards - these may be helpful in this activity.
