### ISSUE TITLE
Set you profile to public

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#117]
When you visit https://github.com/lfenergyarchitecturemodel as non-organization-member, you now only see me being involved in the project. See screenshot 1. It would be great if all our profiles are shown. To realize this, everyone needs to set its profile on https://github.com/orgs/lfenergyarchitecturemodel/people to public.

![Image](https://user-images.githubusercontent.com/3628277/236412239-139c3f17-bd3f-47b8-87ab-64d334122182.png)

**Comment by PrinceAlliander** [comment]
Changed my profile visibility to public.

**Comment by Laurentjg** [comment]
Done the same

**Comment by m-mirz** [comment]
Done

**Comment by RoelandFr** [comment]
Done
