### ISSUE TITLE
Update the model & repo name

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#2]

**Comment by lcrowleyEPRI** [comment]
lfenergyfunctionalarchitecturemodel

**Comment by Jonasvdbo** [comment]
lfenergyfunctionalarchitecturemodel

**Comment by Jonasvdbo** [comment]
The names of the repo and model are updated. If you pull the model in archi, it should update automatically.
