### ISSUE TITLE
Add GXF project

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#25]

**Comment by lcrowleyEPRI** [comment]
Jonas made a start in the GXF folder. Meeting planned with the GXF team.

**Comment by Jonasvdbo** [comment]
Updated GXF view. Is not yet finished.

**Comment by Jonasvdbo** [comment]
@SeanCrimmins Shared DERM example
