### ISSUE TITLE
Add CoMPAS project

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#27]

**Comment by Sander3003** [comment]
@Jonasvdbo can you provide information on what it takes to complete this issue?

**Comment by Jonasvdbo** [comment]
@Sander3003 Yes, I will plan a 30-minute call to discus it.

**Comment by Jonasvdbo** [comment]
Done

**Comment by lcrowleyEPRI** [comment]
Add a definition for configurations data object
