### ISSUE TITLE
Discuss with John how to embed the model in project life cycle

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#41]

**Comment by BenoitJeanson** [comment]
Idea shared with John who suggested to work on it.
The idea was mentioned also during last TAC.
I will remind him.

**Comment by lcrowleyEPRI** [comment]
Can be mentioned at the TAC meeting as part of the role of the official working group.

**Comment by Jonasvdbo** [comment]
Make it part of acceptation criteria of the incubation stage.
