### ISSUE TITLE
Discuss how we can integrate the functional architecture in archimate

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#76]

**Comment by Jonasvdbo** [comment]
See: https://www.lfenergy.org/projects/functional-architecture/

**Comment by PrinceAlliander** [comment]
Business Process, Business Function and Application Functions elements of ArchiMate could be used to model most of the LFE FA. For example, in Customer and Market - Metering and Compensation is a Business Function and is an aggregation of Metering (application/business function), Compensation (business process) and Billing (business process). 
In this way we can make a start and first version.

**Comment by Jonasvdbo** [comment]
Prince can you make a follow-up action / issue?
