### ISSUE TITLE
Update sogno view based on the meta model and functions definitions

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#9]

**Comment by lcrowleyEPRI** [comment]
Need to add a 'SONGO realized' view

**Comment by m-mirz** [comment]
I am working on this in https://github.com/lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel/pull/88

**Comment by PrinceAlliander** [comment]
Based on the meeting on 5th April this issue may be considered as 'Done'

**Comment by m-mirz** [comment]
Yes, I think so too: https://github.com/lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel/pull/88
