### ISSUE TITLE
Add business functions to SOGNO

### ISSUE THREAD

**Issue by Jonasvdbo** [lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel#90]

**Comment by PrinceAlliander** [comment]
Business Functions have been added to the SOGNO project architecture and also mapped 1-1 to the LFE functional architecture. Further update to be provided in the next architecture meeting. 
Next action - push the changes/new architecture to the main branch.

**Comment by m-mirz** [comment]
I have added the mapping to the functional architecture in https://github.com/lfenergyarchitecturemodel/lfenergyfunctionalarchitecturemodel/pull/88
